---
title: "Evidencia_2"
output: word_document
date: "2023-05-07"
---
## Analizar las secuencias de SARS-CoV-2 reportadas en los 20 países con más casos reportados.
```{r}
# Librerias
library(Biostrings)
library(seqinr)
library(adegenet)
library(ape)
library(DECIPHER)
library(ggplot2)
library(ggtree)

# Virus de los 20 paises
virus <- c("ON110425.1","OQ918255.1","MW322968.1","OQ672892.1","OQ921106.1","OQ804217.1","ON797392.1","OL738656.1","OQ847681.1","OQ718959.1","OL549281.1","ON115270.1","OQ592578.1","OP604177.2","MW692794.1","OL989073.1","OM287553.1","MZ359830.1","OQ082914.1","MZ047082.1")

paises = c("USA","IND","FRA","DEU","BRA","JPN","KOR","ITA","GBR","RUS","TUR","ESP","VNM","AUS","TWN","ARG","NLD","IRN","MEX","POL")

# Cargar las secuencias 
virus_sequences <- read.GenBank(virus)

names(virus_sequences) = paises

write.FASTA(virus_sequences,file ="virus_seqs.fasta", append = FALSE)
```
```{r}
sequencias <- read.fasta(file = "virus_seqs.fasta",seqtype =c("DNA"),set.attributes = FALSE, as.string = FALSE)

```

```{r}
# Función para contar la composición de la sequencia
count <- function(seq){
  
  lista_resultados <<- list()
  lista_resultados_T <<- list()
  lista_resultados_A <<- list()
  lista_resultados_C <<- list()
  lista_resultados_G <<- list()
  
  for (i in 1:length(seq)){
  
  seq_i = seq[i]
  
  seq_i = c(as.character(seq_i[[1]]))
    
  n <- length(seq_i)
  a = 0
  t = 0
  c = 0
  g = 0
  
  for(element in 1:n){
    
    if(seq_i[element] == "t"){
    t = t + 1
    
    } else if(seq_i[element] == "a"){
    a = a + 1  
    
    } else if(seq_i[element] == "c"){
    c = c + 1  
    
    } else if(seq_i[element] == "g"){
    g = g + 1
    }
  }
  
  resultados = t+a+c+g
  lista_resultados[[i]] <<- resultados
  lista_resultados_T[[i]] <<- t
  lista_resultados_A[[i]] <<- a
  lista_resultados_C[[i]] <<- c
  lista_resultados_G[[i]] <<- g
  }
  
  data_total <<- data.frame(
    "Total" = c(unlist(lista_resultados)),
    "paises" = paises
  )
  
  data_t <<- data.frame(
    "T" = c(unlist(lista_resultados_T)),
    "paises" = paises
  )
  data_a <<- data.frame(
    "A" = c(unlist(lista_resultados_A)),
    "paises" = paises
  )
  data_c <<- data.frame(
    "C" = c(unlist(lista_resultados_C)),
    "paises" = paises
  )
  data_g <<- data.frame(
    "G" = c(unlist(lista_resultados_G)),
    "paises" = paises
  )
  
}

count(sequencias)
```

```{r fig.align="center", echo = FALSE,fig.width = 14}
 # library
library(ggplot2)
library("gridExtra")

# Grouped
plot_t <- ggplot(data = data_t, aes(x = paises, y = T)) +
       geom_bar(stat = "identity",position = "dodge",alpha = 0.5)+
       geom_text(aes(label = T), vjust = -0.2, size = 2.5,
            position = position_dodge(0.9))+
        ggtitle("Composición de Uracilo por país") +
        xlab("Países")+
        ylab("Uracilo")

options(repr.plot.width=30, repr.plot.height=8)

plot_a <- ggplot(data = data_a, aes(x = paises, y = A)) +
       geom_bar(stat = "identity",position = "dodge",alpha = 0.5)+
       geom_text(aes(label = A), vjust = -0.2, size = 2.5,
            position = position_dodge(0.9))+
    ggtitle("Composición de Adeninas por país") +
        xlab("Países")+
        ylab("Adeninas")

plot_c <- ggplot(data = data_c, aes(x = paises, y = C)) +
       geom_bar(stat = "identity",position = "dodge",alpha = 0.5)+
       geom_text(aes(label = C), vjust = -0.2, size = 2.5,
            position = position_dodge(0.9))+
    ggtitle("Composición de Citosinas por país") +
        xlab("Países")+
        ylab("Citosinas")

plot_g <- ggplot(data = data_g, aes(x = paises, y = G)) +
       geom_bar(stat = "identity",position = "dodge",alpha = 0.5)+
       geom_text(aes(label = G), vjust = -0.2, size = 2.5,
            position = position_dodge(0.9))+
    ggtitle("Composición de Guaninas por país") +
        xlab("Países")+
        ylab("Guaninas")

grid.arrange(plot_t, plot_a, plot_c, plot_g, nrow = 2, ncol = 2)

#grid.arrange(plot_t, plot_a, plot_c, plot_g,
#             layout_matrix = matrix(c(1, 2, 3, 4), ncol = 2))
```

```{r}
ggplot(data = data_total, aes(x = paises, y = Total.Nucleotidos)) +
       geom_bar(stat = "identity",position = "dodge",alpha = 0.5)+
       geom_text(aes(label = Total.Nucleotidos), vjust = -0.5, size = 2.5,
            position = position_dodge(1))+
        ggtitle("Largo de secuencia por país") +
        xlab("Países")+
        ylab("Num. Nucleótidos")+
        ylim(0,35000)


```

```{r fig.align="top", echo = FALSE,fig.width = 14}
virus_seq_no_alineadas <- readDNAStringSet("virus_seqs.fasta", format = "fasta",use.names = TRUE)
virus_seq_no_alineadas <- OrientNucleotides(virus_seq_no_alineadas)
virus_align_seqs <- AlignSeqs(virus_seq_no_alineadas)
writeXStringSet(virus_align_seqs, file = "virus_align_seq.fasta")
virus_aligned <- read.alignment("virus_align_seq.fasta", format = "fasta") 
matriz_distancia <- dist.alignment(virus_aligned, matrix = "similarity")
virus_filogenetico <- nj(matriz_distancia)
class(virus_filogenetico)
virus_plot_filogenetico <- ladderize(virus_filogenetico)
```

```{r fig.align="top", echo = FALSE,fig.width = 10}
plot(virus_plot_filogenetico, bg = "#F0FFF0")
title("SARS_COV2 por país")
ggtree(virus_plot_filogenetico, layout="equal_angle")+geom_tiplab()
```

